### ISSUE TITLE
MS SQL Support

### ISSUE THREAD

**Issue by AdamGerthel** [tmont/node-sql-generate#4]
I would love to see MS SQL support. Let me know if you need any help. I can prob. set up a test database if needed.

**Comment by patrickdevivo** [comment]
+1

**Comment by edudutra** [comment]
Hi everyone.

I've needed it to. So I forked the repo and added MSSQL support. I've implemented all tests to MSSQl dialect and all tests are running ok. 

https://github.com/edudutra/node-sql-generate/commit/881bf0ac64f4607fa82a41af62b3866eef859d73 

The problem is: To test the MSSQL part, I used a ``vagrant`` box (https://github.com/leezu/vagrant-mssql-express/) running Windows with MSSQL Express. The caveat is that this box takes about 3.8GB download. After installed, it consumes 12GB on your disk. I could add it to the vagrant file, but even considering this acceptable, we still can run the test in Travis.

Any thoughts on that? 

I would love to create a PR.

**Comment by tmont** [comment]
Hi @edudutra. Definitely create a PR! I'd rather have the code in there even if it's hard/impossible to test. We could just set up a multi-box vagrant environment and add some caveats to the README about testing on Windows if need be.

Or maybe we could just mock some of the stuff MSSQL connection stuff perhaps? That might be more work than it's worth, though.

Go ahead and submit a PR for sure though.

Thanks!
